apiVersion: apps/v1
kind: Deployment
metadata:
  name: unomarket-frontend
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unomarket-front
  template:
    metadata:
      labels:
        app: unomarket-front
    spec:
      containers:
      - name: web
        image: ludanieldori/unomarket-front:v7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
