server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
    # Redirigir el tráfico de la API hacia el backend interno de Kubernetes
    location /api/ {
        proxy_pass http://backend-service.unomarket.svc.cluster.local:8080/api/;
    }
}